[project]
name = "comfyui-rb-command"
description = "Execute shell commands/scripts with dynamic inputs, and result caching. Supports placeholders ({input0}, {seed}) and environment variables ($INPUT_0, $SEED, etc.)."
version = "1.0.0"
license = { file = "LICENSE" }
dependencies = ["numpy", "Pillow", "scipy"]

[project.urls]
Repository = "https://github.com/itribs/comfyui-rb-command"
Documentation = "https://github.com/itribs/comfyui-rb-command/blob/main/README.md"
"Bug Tracker" = "https://github.com/itribs/comfyui-rb-command/issues"

[tool.comfy]
PublisherId = "itribs"
DisplayName = "comfyui-rb-command"
Icon = ""
